[project]
name = '{{ cookiecutter.project_slug }}'
version = '0.0.0'
description = {{ cookiecutter.description | tojson }}
authors = [{ name = {{ cookiecutter.author_name | tojson }}, email = {{ cookiecutter.author_email | tojson }} }]
requires-python = '>={{ cookiecutter.python_version }}'

[tool.semantic_release]
tag_format = 'v{version}'
commit_message = 'chore(release): v{version} [skip ci]'

[tool.semantic_release.branches.deploy]
match = '{{ cookiecutter.deploy_branch }}'

[tool.semantic_release.changelog]
mode = 'update'
insertion_flag = '<!-- version list -->'

[tool.ruff]
target-version = 'py{{ cookiecutter.python_version | replace('.', '') }}'
line-length = 100
extend-exclude = ['*.md']

[tool.ruff.lint]
select = ['E', 'F', 'W', 'I', 'B', 'UP']

[tool.ruff.format]
quote-style = 'single'

[tool.mypy]
python_version = '{{ cookiecutter.python_version }}'
files = ['src']
mypy_path = 'src'
explicit_package_bases = true
disallow_untyped_defs = true
warn_unused_ignores = true
ignore_missing_imports = true

[tool.coverage.run]
source = ['src']

[tool.coverage.report]
exclude_also = ["if __name__ == .__main__.:"]
